{
    'name': 'Order Type',
    'version': '12.0.0.19',
    'category': 'Tools',
    'summary': "Module for customized fields.",
    'depends': ['base','product','sale','crm','lead_products','stock_account'],
    'author': "Prixgen Tech Solutions Pvt. Ltd.",
    'website': 'https://www.prixgen.com',
    'company': 'Prixgen Tech Solutions Pvt. Ltd.',
    'data': ['views/product_template.xml',
            'views/sale_order_line.xml',
            'views/account_invoice.xml',
             ],
    'auto_install': False,
    'application': True,
}
