from . import account_invoice
from . import account_payment
from . import crm_lead
from . import custom_fields
from . import hr_contract
from . import hr_employee
from . import lic_policy_details
from . import mrp_production
from . import order_type
from . import purchase_order
from . import res_company
from . import res_partner
from . import sale_order
from . import stock_inventory
from . import stock_picking