{
    'name': 'Addon Fields For MCL',
    'summary': "Fields For MCL created by vinutha",
    'version': '12.0.0.17',
    'author': 'Prixgen Tech Solutions Pvt Ltd.',
    'company': 'Prixgen Tech Solutions Pvt Ltd.',
    'website': 'https://www.prixgen.com',
    'depends': ['base','sale','l10n_in_hr_payroll','purchase','product','crm','walkin_sales','sale_management','hr','mrp','hr_contract','Standard_fields_required_HRMS','order_qty','account','account_accountant','prix_analytic_account','analytical_warehouse','letter_of_credit','stock',],
    'data': [
        'views/account_invoice_views.xml',
        'views/crm_lead_views.xml',
        'views/custom_fields_views.xml',
        'views/hr_contract_views.xml',
        'views/hr_employee_views.xml',
        'views/mrp_production_views.xml',
        'views/purchase_order_views.xml',
        'views/res_company.xml',
        'views/res_partner.xml',
        'views/sale_order_views.xml',
        'views/stock_inventory_views.xml',
        'views/acccount_payment.xml',
        'views/stock_picking_form_view.xml',
        ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
